ALTER TABLE `s_order_number`
	COMMENT='订单编号生成表',
	CHANGE COLUMN `date` `date` VARCHAR(50) NULL DEFAULT NULL COMMENT '订单生成日期' FIRST,
	CHANGE COLUMN `name` `name` VARCHAR(100) NULL DEFAULT NULL COMMENT '订单名称' AFTER `date`,
	CHANGE COLUMN `number` `number` INT(11) NULL DEFAULT NULL COMMENT '订单总数' AFTER `name`,
	CHANGE COLUMN `remark` `remark` VARCHAR(100) NULL DEFAULT NULL COMMENT '备注' AFTER `number`,
	CHANGE COLUMN `type` `type` VARCHAR(20) NULL DEFAULT NULL COMMENT '订单类型' AFTER `remark`;
